SELECT COUNT(*) FROM raw.orders;
SELECT COUNT(*) FROM raw.customers;
SELECT COUNT(*) FROM raw.order_items;
SELECT COUNT(*) FROM raw.geolocations;
SELECT COUNT(*) FROM raw.sellers;
SELECT COUNT(*) FROM raw.products;
SELECT COUNT(*) FROM raw.order_reviews;
SELECT COUNT(*) FROM raw.order_payments;
SELECT COUNT(*) FROM raw.category_translations;